// Components data will be here

const allcomponents = [
  {
    id: 1,
    name: "bullet list",
    tag: "ul",
    icon: "list",
    subtag: "li",
    appliedOnlyOnce: false,
    canBeEdited: true,
    editText: "nonEditable",
    editSubtext: [
      "Sample bullet 1",
      "Sample bullet 2",
      "Sample bullet 3",
      "Sample bullet 4",
    ],
    editImg: "nonEditable",
    bootstrapTags: "",
  },
  {
    id: 2,
    name: "button",
    tag: "button",
    icon: "hand-pointer",
    subtag: "notApplicable",
    appliedOnlyOnce: false,
    canBeEdited: true,
    editText: "Sample button",
    editSubtext: "nonEditable",
    editImg: "nonEditable",
    bootstrapTags: "btn btn-secondary",
  },
  {
    id: 3,
    name: "social media link",
    tag: "a",
    icon: "link",
    subtag: "notApplicable",
    appliedOnlyOnce: false,
    canBeEdited: true,
    editText: "Sample social link",
    editSubtext: "nonEditable",
    editImg: "nonEditable",
    bootstrapTags: "",
  },
  {
    id: 4,
    name: "header with logo",
    tag: "header",
    icon: "address-card",
    subtag: "notApplicable",
    appliedOnlyOnce: true,
    canBeEdited: true,
    editText: "Sample header text",
    editSubtext: "nonEditable",
    editImg: "editable",
    bootstrapTags: "navbar navbar-expand-lg navbar-light bg-light",
  },
  {
    id: 5,
    name: "text with tittle",
    tag: "div",
    icon: "text-height",
    subtag: ["h1", "p"],
    appliedOnlyOnce: false,
    canBeEdited: false,
    editText: "nonEditable",
    editSubtext: ["Title example", "lorem ipsum text"],
    editImg: "nonEditable",
    bootstrapTags: "",
  },
];

export default allcomponents;
